version: "3.8"

services:
  # pg-basebackup:
  #   build:
  #     dockerfile: Dockerfile
  #   environment:
  #     - PGPASSWORD=binh123
  #     # - PGDATA=/data
  #   volumes:
  #     - ./pgdata:/data
  #   # - ./script:/script
  #   networks:
  #     - postgres

  replica-db:
    # depends_on:
    #   - pg-basebackup
    container_name: replica-db
    command: "postgres -c config_file=/config/postgresql.conf"
    image: postgres:15
    environment:
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgresdb
      - PGDATA=/data
    volumes:
      - ./pgdata:/data
      - ./config:/config
      - ./archive:/mnt/server/archive
    ports:
      - 5002:5432
    networks:
      - postgres

networks:
  postgres:
    external: true
