-- CREATE USER replicationUser WITH REPLICATION ENCRYPTED PASSWORD 'root123';
-- CREATE ROLE  WITH REPLICATION LOGIN PASSWORD 'root123';

CREATE USER binh REPLICATION LOGIN ENCRYPTED PASSWORD 'binh123';

